# -*- coding: utf-8 -*-
"""Spark and Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1InY-CulXDNGw9Vapf0YM5SFi7-iFFAEN

# Install Py Spark
"""

!pip install pyspark

"""# Load required libraries"""

# Commented out IPython magic to ensure Python compatibility.
# checks if libarires are loaded if not run the code block above
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
from pyspark import SparkContext
!pip install ipython-autotime
# %load_ext autotime

try:
    sc = SparkContext('local', 'my_context')
except ValueError:
    print('Spark_Context already exists!')

from pyspark.sql import SparkSession
try:
    spark = SparkSession.builder.appName('pyspark_session_2').getOrCreate()
except ValueError:
    print('Spark_Session already exists!')

"""# Load CSV in Pandas"""

# Commented out IPython magic to ensure Python compatibility.
# %time
path = "/content/yelp_academic_dataset_tip.json"
pandas_dataframe = pd.read_csv(path,error_bad_lines=False)
pandas_dataframe.head()

"""# Load Data using Spark"""

# Commented out IPython magic to ensure Python compatibility.
# %time
spark_dataframe = spark.read.csv(path, header=True, inferSchema=True)
print(spark_dataframe.show(5))

"""#  Summary Statistics

## In Pandas
"""

# Commented out IPython magic to ensure Python compatibility.
# %time
pandas_dataframe.describe()

"""## In Spark"""

# Commented out IPython magic to ensure Python compatibility.
# %time
spark_dataframe.describe().show(truncate=True)

"""# Missing Data Senarios

## In Pandas

Pandas DataFrame provides a fillna() function that can fill missing data items with any string or number. 

Spark DataFrames provide a similar function, but they only allow a value that matches the data type of the corresponding column.
"""

pandas_dataframe.fillna('NA', inplace = True)
pandas_dataframe.fillna(0, inplace = True)

"""## In Spark"""

spark_dataframe = spark_dataframe.na.fill(0)